### ISSUE TITLE
More than one system address for each X-245 controller?

### ISSUE THREAD

**Issue by jnasholm** [kroimon/uponor-smatrix-analysis#1]
Thank you for the excellent work on this component. Quite impressive!

I have just started experimenting with this on a brand new X-245 controller and four T-149 room thermostats. First test was with just one thermostat and everything worked perfectly. After adding the other thermostats, I noticed that only three of them would show up in the configuration dump log. One thermostat was always unavailable.

After numerous combinations of thermostat registration attempts, different number of thermostats, several factory resets of controller and thermostats, I confirmed an observation. The first registered thermostat, regardless of which out of the four, called the controller by a system address (0x1107) which the other thermostats registered later did not. Those thermostats used the same system address (0x110D) all three of them, but not the system address (0x1107) the first thermostat used.

The first thermostat and the three other thermostats do in fact communicate with the controller, switching registered channels on and off as expected when I change the temperature set-point. Serial communication with the ESP32 apparently also works as expected. One specific warning appeared frequently in the log output; "Received packet from unknown system address ...".

Digging into the component code to find some clue to what was going on, I came across the system address comparison logic; a fundamental decision or assumption that there can only be _one_ system address.

Slight modification of the code as shown bellow confirmed that the first thermostat called the controller by the "unknown system address". Somewhat dirty change to comment out the "return true;" also confirmed that serial communication was functioning. All four thermostats became available and temperature, humidity and set-point, was reported correctly.

```
--- uponor_smatrix.cpp.orig	2025-01-22 21:30:36
+++ uponor_smatrix.cpp	2025-02-26 21:26:55
@@ -106,8 +106,8 @@
     this->address_ = system_address;
   } else if (this->address_ != system_address) {
     // This should never happen except if the system address was set or detected incorrectly, so warn the user.
-    ESP_LOGW(TAG, "Received packet from unknown system address 0x%04X", system_address);
-    return true;
+    ESP_LOGW(TAG, "Received packet for unconfigured system address 0x%04X from device address 0x%04X", system_address, device_address);
+    //return true;
   }
```

Even though this (less than professional) code modification made all four thermostats available, the first one is not controllable from the ESP32 or Home Assistant, as the other three thermostats are. Maybe because the instruction sent to the first thermostat's device address does not have the expected system address (0x1107) as sender address.

To conclude, if this observation is not totally unique, we need a way to configure the component with more than one system address. Also design a way to define which device addresses are tied to each system address. For example:

```yaml
uponor_smatrix:
  - address: 0x1107
    devices:
      - address: 0x9BC7
  - address: 0x110D
    devices:
      - address: 0x1E6D
      - address: 0x1FAB
      - address: 0x1FF4
```

Please advice if this functionality is already implemented but not described in the component documentation.

**Comment by kroimon** [comment]
Hi Jonas!

Thanks a lot for your report! I only ever could go by what I saw other people analyze in forum posts and what I saw others do in their code and match that to my own system. I haven't seen anyone report that the first two bytes of each packet are different for different thermostats, but maybe the analysis that these two bytes are a system address is wrong.
It is possible that the first four bytes are in fact just the device address and there is no such thing as a system or controller address.

I think I can adapt the `uponor_smatrix` component in ESPHome so that the device address is 32 bits (four bytes) instead of the current 16 bits (two bytes), eliminating the system address altogether. This should be possible to implement in a backward-compatible way.
And even if the first and second 16 bits have any additional meaning, I don't think this change would hurt.

Out of curiosity, could you enable debug logging on your UART component and post some logs of received packets from all of your thermostats? Maybe we can learn some more things from your setup.

**Comment by jnasholm** [comment]
Hi Stefan!

Your ideas seem reasonable. I would be happy to test the modified code on my setup.

I am also happy to share debug logging from the UART. I sent you an invitation to the repository where I will share the log files. The repository is not public yet, but will be sometimes in the future.

**Comment by kroimon** [comment]
I have an experimental branch now at [kroimon/esphome@uponor_addresses](https://github.com/kroimon/esphome/tree/uponor_addresses) that gets rid of the system address altogether in favor of 32 bit device addresses.
It should work out of the box with your existing configuration (given you didn't specify the system address before).

As long as the 16 bit device addresses are unique, you can just use your existing configuration and it will work.
Otherwise, it is possible to specify the full 32 bit address now:
```
external_components:
  - source: github://kroimon/esphome@uponor_addresses
    components: [ uponor_smatrix ]

uponor_smatrix:

climate:
  - platform: uponor_smatrix
    name: "Kök"
    address: 0x110D1E6D
  - platform: uponor_smatrix
    name: "Hall"
    address: 0x110D1FAB
  - platform: uponor_smatrix
    name: "Duschrum"
    address: 0x110D1FF4
  - platform: uponor_smatrix
    name: "Vardagsrum"
    address: 0x11079BC7
```

Please test and report if it works for you. If it does, I will prepare a PR for upstream ESPHome.
